import AppConfig from '@/layout/AppConfig'
import Head from 'next/head'
import Link from 'next/link'
import { Button } from 'primereact/button'

const Home = () => {
  return (
    <>
      <Head>
        <title>Alma Tv main page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="surface-0 flex justify-content-center">
        <Link href='/admin/banners/main'>
          <Button label="Login" className="p-button-text p-button-rounded border-none font-light line-height-2 text-blue-500"></Button>
        </Link>
      </div>
    </>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <>
      {page}
      <AppConfig simple />
    </>
  )
}

export default Home