import Carousel from '@/components/Carousel'
import Head from 'next/head'
import Link from 'next/link'
import { Button } from 'primereact/button'
import { useEffect, useState } from 'react'

import { HydrationProvider, Client } from 'react-hydration-provider'

const Home = () => {

  return (
    <>
      <Head>
        <title>Alma Tv main page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="surface-0 flex justify-content-center">
        <Link href='/auth/login'>
          <HydrationProvider>
            <Client>
              <Button label="Вход" className="p-button-text p-button-rounded border-none font-light line-height-2 text-blue-500"></Button>
            </Client>
          </HydrationProvider>
        </Link>
      </div>

      <Carousel />

    </>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <>
      {page}
    </>
  )
}

export default Home